# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CreateOptimData <- function(C_list, X_list, Z_list, D_list, w_diag, V0_list, max_obs, weights, exp_cond) {
    .Call(`_glmmrOptim_CreateOptimData`, C_list, X_list, Z_list, D_list, w_diag, V0_list, max_obs, weights, exp_cond)
}

CreateOptim <- function(dataptr, derivptr, idx_in, n, nmax, robust_log = FALSE, trace = TRUE, kr = FALSE, uncorr = FALSE, bayes = FALSE) {
    .Call(`_glmmrOptim_CreateOptim`, dataptr, derivptr, idx_in, n, nmax, robust_log, trace, kr, uncorr, bayes)
}

CreateDerivatives <- function() {
    .Call(`_glmmrOptim_CreateDerivatives`)
}

FindOptimumDesign <- function(dptr_, type_) {
    .Call(`_glmmrOptim_FindOptimumDesign`, dptr_, type_)
}

AddDesignDerivatives <- function(dptr_, mptr_, is_gaussian_) {
    invisible(.Call(`_glmmrOptim_AddDesignDerivatives`, dptr_, mptr_, is_gaussian_))
}

#' Disable or enable parallelised computing
#' 
#' By default, the package will use multithreading for many calculations if OpenMP is 
#' available on the system. For multi-user systems this may not be desired, so parallel
#' execution can be disabled with this function.
#' 
#' @param parallel_ Logical indicating whether to use parallel computation (TRUE) or disable it (FALSE)
#' @param cores_ Number of cores for parallel execution
#' @return None, called for effects
setParallelOptim <- function(parallel_, cores_ = 2L) {
    invisible(.Call(`_glmmrOptim_setParallelOptim`, parallel_, cores_))
}

